//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./forecast_types');
//HELPER FUNCTIONS AND STRUCTURES

WeatherService_ping_args = function(args) {
};
WeatherService_ping_args.prototype = {};
WeatherService_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WeatherService_ping_args.prototype.write = function(output) {
  output.writeStructBegin('WeatherService_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WeatherService_ping_result = function(args) {
};
WeatherService_ping_result.prototype = {};
WeatherService_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WeatherService_ping_result.prototype.write = function(output) {
  output.writeStructBegin('WeatherService_ping_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WeatherService_getForecast_args = function(args) {
  this.date = null;
  if (args) {
    if (args.date !== undefined) {
      this.date = args.date;
    }
  }
};
WeatherService_getForecast_args.prototype = {};
WeatherService_getForecast_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.date = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WeatherService_getForecast_args.prototype.write = function(output) {
  output.writeStructBegin('WeatherService_getForecast_args');
  if (this.date !== null && this.date !== undefined) {
    output.writeFieldBegin('date', Thrift.Type.STRING, 1);
    output.writeString(this.date);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WeatherService_getForecast_result = function(args) {
  this.success = null;
  this.ire = null;
  if (args instanceof ttypes.InvalidRequestException) {
    this.ire = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ire !== undefined) {
      this.ire = args.ire;
    }
  }
};
WeatherService_getForecast_result.prototype = {};
WeatherService_getForecast_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Forecast();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ire = new ttypes.InvalidRequestException();
        this.ire.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WeatherService_getForecast_result.prototype.write = function(output) {
  output.writeStructBegin('WeatherService_getForecast_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ire !== null && this.ire !== undefined) {
    output.writeFieldBegin('ire', Thrift.Type.STRUCT, 1);
    this.ire.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WeatherServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
WeatherServiceClient.prototype = {};
WeatherServiceClient.prototype.ping = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_ping();
};

WeatherServiceClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid);
  var args = new WeatherService_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

WeatherServiceClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new WeatherService_ping_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
WeatherServiceClient.prototype.getForecast = function(date, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getForecast(date);
};

WeatherServiceClient.prototype.send_getForecast = function(date) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getForecast', Thrift.MessageType.CALL, this.seqid);
  var args = new WeatherService_getForecast_args();
  args.date = date;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

WeatherServiceClient.prototype.recv_getForecast = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new WeatherService_getForecast_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ire) {
    return callback(result.ire);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getForecast failed: unknown result');
};
WeatherServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
WeatherServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

WeatherServiceProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new WeatherService_ping_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.ping(function (err, result) {
    var result = new WeatherService_ping_result((err != null ? err : {success: result}));
    output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

WeatherServiceProcessor.prototype.process_getForecast = function(seqid, input, output) {
  var args = new WeatherService_getForecast_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.getForecast(args.date, function (err, result) {
    var result = new WeatherService_getForecast_result((err != null ? err : {success: result}));
    output.writeMessageBegin("getForecast", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

